### PR TITLE
Initial RI/MI example

### PR DESCRIPTION
**Pull request by kevinmcgarry**

### CODE REVIEW

**Review by odowdj — COMMENTED** [review]
Should the actor id, Organization ids be just guids as opposed to uris?

**Comment by krisiye** [comment]
We also want to find a home for -  RI quiz details? (ID/sequence/score/isPractice etc..) ?
Also The RI score will only be available (meaningful) end of the test. unless we want to capture interim scores along the way in the test.

**Comment by odowdj** [comment]
I think GradeEvent is used for Scores https://www.imsglobal.org/sites/default/files/caliper/v1p1/caliper-spec-v1p1/caliper-spec-v1p1.html#gradeEvent

**Review by krisiye — APPROVED** [review]
Need to keep iterating on further updates to the fixtures - per discussions and comments.

**Pull request merged**
